config/routes.rb
Rails.application.routes.draw do
  get 'lists/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'homes#top'
  resources :lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
     @list = List.new(list_params)
   if @list.save
     redirect_to lists_path
   else
    render :index
   end
  end

  def edit
   @list = List.find(params[:id])
  end

  def update
     @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to list_path(@list.id)
    else
      render :edit
    end
  end

  def destroy
     @list = List.find(params[:id])
    if @list.destroy
       redirect_to lists_path
    else
      render :show
    end
  end

  private
   def list_params
    params.require(:list).permit(:title, :body)
   end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.erb
<h1>Welcome!!</h1>
<%=link_to "Enter", lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
  <h1>編集</h1>
  <%= form_with model:@list, url: list_path(@list), method: :patch, local:true do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '保存' %>
    <%= link_to "削除", list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
  <% end %>

app/views/lists/index.html.erb
<h1>投稿一覧</h1>
<p>タイトル</p>
<% @lists.each do |list| %>
<table>
  <tr>
    <th><%=link_to list.title,list_path(list.id) %></th>
    <th><%=link_to "編集",edit_list_path(list.id) %></th>
    <th><%= link_to "削除", list_path(list.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></th>
  <% end %>
  </tr>
</table>
<table>
  <tr>
    <th><%=link_to "新規投稿",new_list_path %></th>
  </tr>
</table>

app/views/lists/new.html.erb
<h1>新規投稿</h1>
<%= form_with model: @list, url:'/lists', local:true do |f| %>
<h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/lists/show.html.erb
<h2>タイトル</h2>
<p><%= @list.title %></p>
<h2>本文</h2>
<p><%= @list.body %></p>
<%=link_to "投稿一覧画面",lists_path %>
<%=link_to "編集",edit_list_path(@list.id) %>